-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AS AI JOIN ANIMAL_OUTS AS AO 
ON AI.ANIMAL_ID = AO.ANIMAL_ID	 
WHERE DATE_FORMAT(AI.DATETIME, '%Y-%m-%d-%T') > DATE_FORMAT(AO.DATETIME, '%Y-%m-%d-%T')
ORDER BY AI.DATETIME ASC;