-- 코드를 입력하세요
SELECT A.MCDP_CD AS 진료과코드, COUNT(A.APNT_NO) AS 5월예약건수
FROM APPOINTMENT AS A
WHERE DATE_FORMAT(APNT_YMD,'%Y-%M') = DATE_FORMAT('2022-05-01','%Y-%M')
GROUP BY MCDP_CD 
ORDER BY 5월예약건수 ASC, 진료과코드 ASC;
